Repository Kuadrant/limitador-operator, pull requests merged in 2023-08, with the labels that each got.

#82 Go1.19 & actions/checkout@v3 & actions/setup-go@v4
  .github/workflows/build-images-base.yaml
  .github/workflows/test.yaml
  Dockerfile
  doc/development.md
  go.mod
Labels: kind/enhancement, participation/good first issue, size/small

#87 codecov: do not fail ci on error
  .github/workflows/test.yaml
Labels: kind/bug, participation/good first issue, size/small

#89 workflow: pin yq version to v4.34.2
  Makefile
Labels: kind/bug, participation/good first issue, size/small

#92 deployment CR reconcile of containers
  controllers/limitador_controller.go
  controllers/limitador_controller_test.go
  pkg/reconcilers/deployment.go
  pkg/reconcilers/deployment_test.go
  pkg/reconcilers/suite_test.go
Labels: kind/bug, target/current, size/small

#91 Enable configuring PDB from Limitador CR
  Makefile
  api/v1alpha1/limitador_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/limitador-operator.clusterserviceversion.yaml
  bundle/manifests/limitador.kuadrant.io_limitadors.yaml
  config/crd/bases/limitador.kuadrant.io_limitadors.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/limitador_controller.go
  controllers/limitador_controller_test.go
  pkg/limitador/k8s_objects.go
  pkg/limitador/k8s_objects_test.go
  pkg/reconcilers/base_reconciler.go
  pkg/reconcilers/poddisruptionbudget.go
Labels: kind/enhancement, participation/good first issue, target/current, size/small, area/api
